import streamlit as st
import pandas as pd
import psycopg2
import time
import os

# Configure the Streamlit page layout
st.set_page_config(page_title="Eagle Vision Dashboard", layout="wide")
st.title("🏗️ Construction Equipment Utilization Dashboard")

# Safely connect to PostgreSQL and fetch the latest logs
def get_data():
    try:
        conn = psycopg2.connect("host=db dbname=equipment_db user=user password=pass")
        df = pd.read_sql("SELECT * FROM equipment_logs ORDER BY id DESC LIMIT 100", conn)
        conn.close()
        return df
    except Exception as e:
        # Return an empty DataFrame if the database is not yet ready
        return pd.DataFrame() 

# Divide the screen into two columns (Video on the left, Analytics on the right)
col1, col2 = st.columns([2, 1])

with col1:
    st.subheader("Live Processed Feed 🔴")
    # Placeholder for the continuously updating video frame
    video_placeholder = st.empty()

with col2:
    st.subheader("Real-time Analytics")
    # Placeholder for the continuously updating metrics
    data_placeholder = st.empty()

# Continuous loop for real-time updates
while True:
    
    # 1. Update the live video feed
    with col1:
        if os.path.exists('latest_frame.jpg'):
            try:
                # Display the latest frame generated by main.py
                video_placeholder.image('latest_frame.jpg', use_container_width=True)
            except Exception as e:
                # Ignore rendering errors if the image is being overwritten at this exact moment
                pass 

    # 2. Update the database metrics
    with col2:
        df = get_data()
        if not df.empty:
            latest = df.iloc[0]
            with data_placeholder.container():
                # Display Key Performance Indicators (KPIs)
                st.metric("Current State", latest['state'])
                st.metric("Current Activity", latest['activity'])
                st.metric("Utilization", f"{latest['utilization_percent']}%")
                st.write("---")
                
                # Display a table of the most recent Kafka logs
                st.write("Recent Kafka Logs:")
                st.dataframe(df[['timestamp_str', 'state', 'activity']].head(10))
        else:
            with data_placeholder.container():
                st.info("Waiting for data stream... Please start main.py")
    
    # Refresh rate (0.5 seconds for smooth updates without overloading Streamlit)
    time.sleep(0.5)